// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.shmoozeatl.com/
// Generated: 2026-06-23T18:46:33.045Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#333333' | '#ffffff' | '#e1ded4' | '#efece6' | '#0099dd' | '#bbbbbb' | '#2288dd' | '#0d121c' | '#f1694f' | '#cdd5df' | '#a9a9a9' | '#1a73e8';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Bitter' | 'Shrikhand' | 'Roboto' | 'SFico' | 'Times' | 'Google Sans Text';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '500';

export type SpacingToken = '1px' | '4px' | '22px' | '30px' | '32px' | '35px' | '38px' | '40px' | '43px' | '48px' | '51px' | '64px' | '77px' | '84px' | '139px' | '146px' | '274px' | '302px' | '323px' | '369px';

export type RadiusToken = '2px' | '12px' | '26px' | '50px' | '300px';

export type DurationToken = '75ms' | '100ms' | '170ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
