// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://www.shmoozeatl.com/
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xE1DED4)
  static let actionSecondary = Color(hex: 0x0099DD)
  static let surfaceDefault = Color(hex: 0xE1DED4)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 4
  static let spacingS2: CGFloat = 22
  static let spacingS3: CGFloat = 30
  static let spacingS4: CGFloat = 32
  static let spacingS5: CGFloat = 35
  static let spacingS6: CGFloat = 38
  static let spacingS7: CGFloat = 40
  static let spacingS8: CGFloat = 43
  static let spacingS9: CGFloat = 48
  static let spacingS10: CGFloat = 51
  static let spacingS11: CGFloat = 64
  static let spacingS12: CGFloat = 77
  static let spacingS13: CGFloat = 84
  static let spacingS14: CGFloat = 139
  static let spacingS15: CGFloat = 146
  static let spacingS16: CGFloat = 274
  static let spacingS17: CGFloat = 302
  static let spacingS18: CGFloat = 323
  static let spacingS19: CGFloat = 369

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 12
  static let radiusR2: CGFloat = 26
  static let radiusR3: CGFloat = 50
  static let radiusR4: CGFloat = 300
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xE1DED4)
  static let brandSecondary = Color(hex: 0x0099DD)
  static let neutralN100 = Color(hex: 0x000000)
  static let neutralN200 = Color(hex: 0x333333)
  static let neutralN300 = Color(hex: 0xFFFFFF)
  static let neutralN400 = Color(hex: 0xEFECE6)
  static let neutralN500 = Color(hex: 0xBBBBBB)
  static let neutralN600 = Color(hex: 0xCDD5DF)
  static let neutralN700 = Color(hex: 0xA9A9A9)
  static let backgroundBg0 = Color(hex: 0xE1DED4)
  static let backgroundBg1 = Color(hex: 0x000000)
  static let backgroundBg2 = Color(hex: 0xFFFFFF)
  static let backgroundBg3 = Color(hex: 0xEFECE6)
  static let backgroundBg4 = Color(hex: 0xAFAFAF)
  static let backgroundBg5 = Color(hex: 0xE5E3DF)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0xFFFFFF)
  static let textText2 = Color(hex: 0x333333)
  static let textText3 = Color(hex: 0xBBBBBB)
  static let textText4 = Color(hex: 0x0D121C)
  static let textText5 = Color(hex: 0x2288DD)
  static let textText6 = Color(hex: 0xF1694F)
}

// typography.body: family=Bitter size=62.08px weight=400 lineHeight=65.5565px
